### PR TITLE
📝 Updated documentation with programmed filling

### PR DESCRIPTION
**Pull request by GautierDele**
Might be good to inform users about the new feature 😄

### CODE REVIEW

**Comment by GautierDele** [comment]
@techouse please verify that this PR won't cause any trouble as I can see my previous commit here
I don't think so but we're never too cautious

**Comment by techouse** [comment]
Well, I have not made any releases yet so I didn't think it necessary to inform anyone just yet. :)

**Comment by GautierDele** [comment]
I understand, if you have any time to push a new release it would be awesome :)

**Comment by techouse** [comment]
Hey, yea I had plans, but work got in the way LOL

I'll do it ASAP.

**Pull request merged**
